name: autolabel
on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: c4illin/autolabel@main
        with:
          type_labels: |
            feat: feature
            fix: fix
            docs: documentation
            style: style
            refactor: refactor
            perf: performance
            test: test
            build: build
            ci: ci
            revert: revert
            breaking: breaking
